### PR TITLE
Use guid

### PR DESCRIPTION
**Pull request by aintgoin2goa**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
is this going to invalidate all our a/b data collected so far?

**Comment by commuterjoy** [comment]
Looks good I think.

We need to make sure the next-beacon is sending the `X-FT-Session-Token` to the AB service, otherwise the events won't be tagged with the correct segment.

https://github.com/Financial-Times/next-beacon/blob/master/models/event.js#L151

**Comment by commuterjoy** [comment]
@matthew-andrews yes. it will invalidate it because hashing on a different uuid will put everyone in different random buckets. Best do it now though rather than during a test.

**Comment by commuterjoy** [comment]
@matthew-andrews also, you've changed your github photo.

**Comment by matthew-andrews** [comment]
makes sense, and yup.

**Comment by aintgoin2goa** [comment]
ok @commuterjoy  I'll make the change to Beacon.  Shall I just add the session header, or replace the user-id header?

**Pull request merged**
