### PR TITLE
Add A/B test for ratings metadata

### PR DESCRIPTION
**Pull request by matthew-andrews**
cc @commuterjoy

### CODE REVIEW

**Comment by commuterjoy** [comment]
Looks good.

Think about a clearer outcome.

Eg. 4 and 5 star ratings visited 20% more when people see the stars.

🌟 🌟 🌟

**Comment by matthew-andrews** [comment]
just worried if i limit it to certain stars there won't be enough traffic…… already it's quite a small subset :see_no_evil:

**Comment by commuterjoy** [comment]
Ok, np.

**Comment by matthew-andrews** [comment]
`<honesty>`partly this is just me wanting to play with the ab testing framework…`</honesty>`

**Pull request merged**
